/* Generated by node tools/build-info.cjs */
globalThis.LB_BUILD = {
  "engineVersion": "lb2027-spherical-0.2.0",
  "baseCommit": "863e3f8aa2803ca02dc78cd9b42a114bec4658c4",
  "sourceSha256": "6512550e44b00e875f082c3dce04e7414a8ce9d8b6bab2b014eeefb05fc81c9d",
  "note": "Source fingerprint identifies this exact working source; baseCommit is its recorded Git parent at stamping time."
};
