/* Generated by node tools/build-info.cjs */
globalThis.LB_BUILD = {
  "applicationVersion": "0.5.2",
  "synthesisEngineVersion": "synthesis-1",
  "engineVersion": "lb2027-spherical-0.4.0",
  "searchEngineVersion": "numerical-lab-2",
  "baseCommit": "12d51d1fa85d83c4a09b35bba6dcae4053599849",
  "sourceSha256": "ff317be386ec7e620492cf28771c4dcd393c7f003f4f59069297ee3906bf40df",
  "note": "Source fingerprint identifies this exact working source; baseCommit is its recorded Git parent at stamping time."
};
