const fs = require("node:fs");
const path = require("node:path");
const crypto = require("node:crypto");
const cp = require("node:child_process");
const root = path.resolve(__dirname, "..");
const files = ["index.html", "style.css", "script.js"];
for (const dir of [
  "materials",
  "optics",
  "analysis",
  "design",
  "optimization",
  "import",
  "ui",
]) {
  for (const file of fs
    .readdirSync(path.join(root, dir))
    .filter((f) => f.endsWith(".js"))
    .sort())
    files.push(`${dir}/${file}`);
}
const hash = crypto.createHash("sha256");
for (const file of files.sort())
  hash.update(file + "\0").update(fs.readFileSync(path.join(root, file)));
const baseCommit = cp
  .execFileSync("git", ["rev-parse", "HEAD"], { cwd: root, encoding: "utf8" })
  .trim();
const info = {
  engineVersion: "lb2027-spherical-0.2.0",
  baseCommit,
  sourceSha256: hash.digest("hex"),
  note: "Source fingerprint identifies this exact working source; baseCommit is its recorded Git parent at stamping time.",
};
fs.writeFileSync(
  path.join(root, "build-info.js"),
  "/* Generated by node tools/build-info.cjs */\nglobalThis.LB_BUILD = " +
    JSON.stringify(info, null, 2) +
    ";\n",
);
console.log(info);
